- hosts: srv-lnx
  
  tasks:
    - file: name={{ item }} state=absent
      when: ansible_os_family == "RedHat" 
      with_items:
        - /usr/local/sbin/inq.Linuxi386
        - /usr/local/sbin/inq.LinuxAMD64
    
    - copy: src=/appl/scripts/inq/inq.LinuxAMD64 dest=/usr/local/sbin/inq mode=0775
      when: ansible_os_family == "RedHat"
