- hosts: srv-lnx
  
  tasks:
    - file: name={{ item }} state=absent
      when: ansible_os_family == "RedHat" 
      with_items:
        - /usr/local/sbin/nmon
    
    - copy: src=/appl/scripts/nmon16e_x86_rhel65 dest=/usr/local/sbin/nmon mode=0775
      when: ansible_os_family == "RedHat" and ansible_distribution_version >= "6.5"
      #when: ansible_os_family == "RedHat" and ansible_distribution_version >= "6.5" and "ansible_machine" == "x86_64"
