- hosts: srv-ocs
  
  tasks:
    - lineinfile: dest=/etc/ssh/sshd_config state=absent line="MACs hmac-sha1,hmac-ripemd160"
      when: ansible_os_family == "RedHat"

    - lineinfile: dest=/etc/ssh/sshd_config state=present line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc"
      when: ansible_os_family == "RedHat"

    - service: name=sshd state=restarted enabled=yes
      when: ansible_os_family == "RedHat"

