- hosts: srv-lnx
  
  tasks:
    - file: name= {{ item }} state=absent
      when: ansible_os_family == "RedHat" 
      with_items:
        - /usr/local/sbin/xsos
    
    - copy: src=/appl/scripts/xsos dest=/usr/local/sbin/xsos mode=0775 owner=root
      when: ansible_os_family == "RedHat" and ansible_distribution_release == "Santiago"
